---
- hosts:
    - '10.200.1.2'
  users:
    - 'amnesia'
  commands:
    SIGNAL:
      - 'NEWNYM'
    GETINFO:
      - 'circuit-status'
      - 'net/listeners/socks'
      - 'ns/id/[a-fA-F0-9]+'
      - 'ip-to-country/\d+\.\d+\.\d+\.\d+'
    ONION_CLIENT_AUTH_ADD:
      - '.+'
  confs:
    bridge:
  events:
    STREAM:
  restrict-stream-events: true
